sonar.projectKey=automation-deployment
sonar.projectName=Automation Deployment Project
sonar.projectVersion=1.0

sonar.sources=src/main
sonar.tests=src/test

sonar.java.binaries=target/classes

sonar.sourceEncoding=UTF-8
