apiVersion: v2

name: automation-deployment

description: Enterprise Helm Chart for Automation Deployment Project

type: application

version: 0.1.0

appVersion: "1.0.0"

kubeVersion: ">=1.30.0"

keywords:
  - java
  - tomcat
  - spring
  - devsecops
  - kubernetes
  - helm

home: https://github.com/muralidhargurram39/automation-deployment-project

maintainers:
  - name: Muralidhar G
