apiVersion: v1
kind: ConfigMap

metadata:
  name: automation-config
  namespace: automation-deployment

data:
  APP_NAME: "automation-deployment"
  APP_ENV: "development"
  APP_VERSION: "1.0"
  LOG_LEVEL: "INFO"
  TZ: "Asia/Kolkata"
