apiVersion: v1
kind: Secret

metadata:
  name: {{ include "automation-deployment.secret" . }}
  namespace: {{ include "automation-deployment.namespace" . }}

  labels:
{{ include "automation-deployment.labels" . | indent 4 }}

type: Opaque

stringData:
  DB_USERNAME: {{ .Values.secret.DB_USERNAME | quote }}
  DB_PASSWORD: {{ .Values.secret.DB_PASSWORD | quote }}
